[DEFECT] NoMethodError: undefined method `Pathname'
Problem: When calling the chdir method, a NoMethod error is thrown with message: "undefined method 'Pathname'"

Analysis: The actual exception is thrown from the private method clean_path, on the following code line:
    Pathname(join_to_pwd(path)).cleanpath.to_path

Fix: Added require for 'pathname'

Ruby version: 2.4.2